; FF8 Remastered: Demaster patch config file
;1.2.8a
DIRECT_IO=1
;[CORE]- loads files from unpacked archives
UV_PATCH=1
;Fixes worldmap UV issues significantly improving graphic
LOG=1
;Outputs logs to demaster.txt
MORE_DEBUG_OUTPUT_PATCH=0
;outputs rich engine data to debug console - now stable!
BATTLE_CHARACTER=1
;Disables battle characters texture resolution limit 
FIELD_ENTITY=1
;Disables field entities texture resolution limit
BATTLE_HOOK_MONSTER_FIELDS=1
;Enables support for new/custom texture of battle stages and monsters
FIELD_BACKGROUND=1
;Enables support for loading custom field backgrounds
WORLD_TEXTURES=1
;[UNSTABLE] Enables support for loading custom worldmap textures
LINEAR_PATCH=1
;Disables linear filtering and brings back point clamp as in PlayStation
OPENGL_HOOK=0
;Enables all sorts of functions for OpenGl
DEVELOPER=0
;Enables powerful developer window for debugging, research and modding [BETA]
;BATTLE_STAGE_ANIMATION_DELAY=100
;In milliseconds, if this number is too low it may skip frames.
;BATTLE_STAGE_FORCE_RELOAD=1
;Causes textures to reload when requested from game. This might need to start a new battle.
FILL_ASPECT_RATIO=0
;Stretch the 4:3 to 16:9 aspect ratio
HASH_ENABLED=1
;Enables hash feature
HASH_OUTPUT=0
;Outputs hashed textures
HASH_OUTPUT_EXT=0
;Keep on 0 for now
HASH_LOAD_HD=1
;Enable loading of HD textures from hash
HASH_LOAD_HD_EXT=1
;Keep on 1 for DDS
IMGUI_DEBUG=0
;Imgui debug mode
SKIP_SPLASH=0
;Skips the splash screen
DEBUG_GLTEXIMAGE2D=0
;Enables debug output for glTexImage2D
